package gridlabd

type MeterData struct {
	Id                                    string `json:"id"`
	Class                                 string `json:"class"`
	Name                                  string `json:"name"`
	Rank                                  string `json:"rank"`
	Clock                                 string `json:"clock"`
	Flags                                 string `json:"flags"`
	MeasuredRealEnergy                    string `json:"measured_real_energy"`
	MeasuredRealEnergyDelta               string `json:"measured_real_energy_delta"`
	MeasuredReactiveEnergy                string `json:"measured_reactive_energy"`
	MeasuredReactiveEnergyDelta           string `json:"measured_reactive_energy_delta"`
	MeasuredEnergyDeltaTimestep           string `json:"measured_energy_delta_timestep"`
	MeasuredPower                         string `json:"measured_power"`
	MeasuredPowerA                        string `json:"measured_power_A"`
	MeasuredPowerB                        string `json:"measured_power_B"`
	MeasuredPowerC                        string `json:"measured_power_C"`
	MeasuredDemand                        string `json:"measured_demand"`
	MeasuredRealPower                     string `json:"measured_real_power"`
	MeasuredReactivePower                 string `json:"measured_reactive_power"`
	MeterPowerConsumption                 string `json:"meter_power_consumption"`
	MeasuredVoltageA                      string `json:"measured_voltage_A"`
	MeasuredVoltageB                      string `json:"measured_voltage_B"`
	MeasuredVoltageC                      string `json:"measured_voltage_C"`
	MeasuredVoltageAB                     string `json:"measured_voltage_AB"`
	MeasuredVoltageBC                     string `json:"measured_voltage_BC"`
	MeasuredVoltageCA                     string `json:"measured_voltage_CA"`
	MeasuredRealMaxVoltageInIntervalA     string `json:"measured_real_max_voltage_in_interval_A"`
	MeasuredRealMaxVoltageInIntervalB     string `json:"measured_real_max_voltage_in_interval_B"`
	MeasuredRealMaxVoltageInIntervalC     string `json:"measured_real_max_voltage_in_interval_C"`
	MeasuredReactiveMaxVoltageInIntervalA string `json:"measured_reactive_max_voltage_in_interval_A"`
	MeasuredReactiveMaxVoltageInIntervalB string `json:"measured_reactive_max_voltage_in_interval_B"`
	MeasuredReactiveMaxVoltageInIntervalC string `json:"measured_reactive_max_voltage_in_interval_C"`
	MeasuredRealMinVoltageInIntervalA     string `json:"measured_real_min_voltage_in_interval_A"`
	MeasuredRealMinVoltageInIntervalB     string `json:"measured_real_min_voltage_in_interval_B"`
	MeasuredRealMinVoltageInIntervalC     string `json:"measured_real_min_voltage_in_interval_C"`
	MeasuredAvgVoltageMagInIntervalA      string `json:"measured_avg_voltage_mag_in_interval_A"`
	MeasuredAvgVoltageMagInIntervalB      string `json:"measured_avg_voltage_mag_in_interval_B"`
	MeasuredAvgVoltageMagInIntervalC      string `json:"measured_avg_voltage_mag_in_interval_C"`
	MeasuredAvgVoltageMagInIntervalAB     string `json:"measured_avg_voltage_mag_in_interval_AB"`
	MeasuredAvgVoltageMagInIntervalBC     string `json:"measured_avg_voltage_mag_in_interval_BC"`
	MeasuredAvgVoltageMagInIntervalCA     string `json:"measured_avg_voltage_mag_in_interval_CA"`
	MeasuredCurrentA                      string `json:"measured_current_A"`
	MeasuredCurrentB                      string `json:"measured_current_B"`
	MeasuredCurrentC                      string `json:"measured_current_C"`
	CustomerInterrupted                   string `json:"customer_interrupted"`
	CustomerInterruptedSecondary          string `json:"customer_interrupted_secondary"`
	MonthlyBill                           string `json:"monthly_bill"`
	PreviousMonthlyBill                   string `json:"previous_monthly_bill"`
	PreviousMonthlyEnergy                 string `json:"previous_monthly_energy"`
	MonthlyFee                            string `json:"monthly_fee"`
	MonthlyEnergy                         string `json:"monthly_energy"`
	BillMode                              string `json:"bill_mode"`
	PowerMarket                           string `json:"power_market"`
	BillDay                               string `json:"bill_day"`
	Price                                 string `json:"price"`
	PriceBase                             string `json:"price_base"`
	FirstTierPrice                        string `json:"first_tier_price"`
	FirstTierEnergy                       string `json:"first_tier_energy"`
	SecondTierPrice                       string `json:"second_tier_price"`
	SecondTierEnergy                      string `json:"second_tier_energy"`
	ThirdTierPrice                        string `json:"third_tier_price"`
	ThirdTierEnergy                       string `json:"third_tier_energy"`
	Bustype                               string `json:"bustype"`
	Busflags                              string `json:"busflags"`
	ReferenceBus                          string `json:"reference_bus"`
	MaximumVoltageError                   string `json:"maximum_voltage_error"`
	VoltageA                              string `json:"voltage_A"`
	VoltageB                              string `json:"voltage_B"`
	VoltageC                              string `json:"voltage_C"`
	VoltageAB                             string `json:"voltage_AB"`
	VoltageBC                             string `json:"voltage_BC"`
	VoltageCA                             string `json:"voltage_CA"`
	CurrentA                              string `json:"current_A"`
	CurrentB                              string `json:"current_B"`
	CurrentC                              string `json:"current_C"`
	PowerA                                string `json:"power_A"`
	PowerB                                string `json:"power_B"`
	PowerC                                string `json:"power_C"`
	ShuntA                                string `json:"shunt_A"`
	ShuntB                                string `json:"shunt_B"`
	ShuntC                                string `json:"shunt_C"`
	PrerotatedCurrentA                    string `json:"prerotated_current_A"`
	PrerotatedCurrentB                    string `json:"prerotated_current_B"`
	PrerotatedCurrentC                    string `json:"prerotated_current_C"`
	CurrentAB                             string `json:"current_AB"`
	CurrentBC                             string `json:"current_BC"`
	CurrentCA                             string `json:"current_CA"`
	CurrentAN                             string `json:"current_AN"`
	CurrentBN                             string `json:"current_BN"`
	CurrentCN                             string `json:"current_CN"`
	PowerAB                               string `json:"power_AB"`
	PowerBC                               string `json:"power_BC"`
	PowerCA                               string `json:"power_CA"`
	PowerAN                               string `json:"power_AN"`
	PowerBN                               string `json:"power_BN"`
	PowerCN                               string `json:"power_CN"`
	ShuntAB                               string `json:"shunt_AB"`
	ShuntBC                               string `json:"shunt_BC"`
	ShuntCA                               string `json:"shunt_CA"`
	ShuntAN                               string `json:"shunt_AN"`
	ShuntBN                               string `json:"shunt_BN"`
	ShuntCN                               string `json:"shunt_CN"`
	MeanRepairTime                        string `json:"mean_repair_time"`
	FrequencyMeasureType                  string `json:"frequency_measure_type"`
	SfmTf                                 string `json:"sfm_Tf"`
	PllKp                                 string `json:"pll_Kp"`
	PllKi                                 string `json:"pll_Ki"`
	MeasuredAngleA                        string `json:"measured_angle_A"`
	MeasuredFrequencyA                    string `json:"measured_frequency_A"`
	MeasuredAngleB                        string `json:"measured_angle_B"`
	MeasuredFrequencyB                    string `json:"measured_frequency_B"`
	MeasuredAngleC                        string `json:"measured_angle_C"`
	MeasuredFrequencyC                    string `json:"measured_frequency_C"`
}

func (cd MeterData) className() string {
	return "meter"
}
