package gridlabd

type TriplexMeterData struct {
	Id                                 string `json:"id"`
	Name                               string `json:"name"`
	Rank                               string `json:"rank"`
	Clock                              string `json:"clock"`
	Flags                              string `json:"flags"`
	MeasuredRealEnergy                 string `json:"measured_real_energy"`
	MeasuredRealEnergyDelta            string `json:"measured_real_energy_delta"`
	MeasuredReactiveEnergy             string `json:"measured_reactive_energy"`
	MeasuredReactiveEnergyDelta        string `json:"measured_reactive_energy_delta"`
	MeasuredEnergyDeltaTimestep        string `json:"measured_energy_delta_timestep"`
	MeasuredPower                      string `json:"measured_power"`
	IndivMeasuredPower1                string `json:"indiv_measured_power_1"`
	IndivMeasuredPower2                string `json:"indiv_measured_power_2"`
	IndivMeasuredPowerN                string `json:"indiv_measured_power_N"`
	MeasuredDemand                     string `json:"measured_demand"`
	MeasuredRealPower                  string `json:"measured_real_power"`
	MeasuredReactivePower              string `json:"measured_reactive_power"`
	MeterPowerConsumption              string `json:"meter_power_consumption"`
	MeasuredVoltage1                   string `json:"measured_voltage_1"`
	MeasuredVoltage2                   string `json:"measured_voltage_2"`
	MeasuredVoltage12                  string `json:"measured_voltage_12"`
	MeasuredVoltageN                   string `json:"measured_voltage_N"`
	MeasuredRealMaxVoltage1InInterval  string `json:"measured_real_max_voltage_1_in_interval"`
	MeasuredRealMaxVoltage2InInterval  string `json:"measured_real_max_voltage_2_in_interval"`
	MeasuredRealMaxVoltage12InInterval string `json:"measured_real_max_voltage_12_in_interval"`
	MeasuredImagMaxVoltage1InInterval  string `json:"measured_imag_max_voltage_1_in_interval"`
	MeasuredImagMaxVoltage2InInterval  string `json:"measured_imag_max_voltage_2_in_interval"`
	MeasuredImagMaxVoltage12InInterval string `json:"measured_imag_max_voltage_12_in_interval"`
	MeasuredRealMinVoltage1InInterval  string `json:"measured_real_min_voltage_1_in_interval"`
	MeasuredRealMinVoltage2InInterval  string `json:"measured_real_min_voltage_2_in_interval"`
	MeasuredRealMinVoltage12InInterval string `json:"measured_real_min_voltage_12_in_interval"`
	MeasuredImagMinVoltage1InInterval  string `json:"measured_imag_min_voltage_1_in_interval"`
	MeasuredImagMinVoltage2InInterval  string `json:"measured_imag_min_voltage_2_in_interval"`
	MeasuredImagMinVoltage12InInterval string `json:"measured_imag_min_voltage_12_in_interval"`
	MeasuredAvgVoltageMag1InInterval   string `json:"measured_avg_voltage_mag_1_in_interval"`
	MeasuredAvgVoltageMag2InInterval   string `json:"measured_avg_voltage_mag_2_in_interval"`
	MeasuredAvgVoltageMag12InInterval  string `json:"measured_avg_voltage_mag_12_in_interval"`
	MeasuredCurrent1                   string `json:"measured_current_1"`
	MeasuredCurrent2                   string `json:"measured_current_2"`
	MeasuredCurrentN                   string `json:"measured_current_N"`
	CustomerInterrupted                string `json:"customer_interrupted"`
	CustomerInterruptedSecondary       string `json:"customer_interrupted_secondary"`
	MonthlyBill                        string `json:"monthly_bill"`
	PreviousMonthlyBill                string `json:"previous_monthly_bill"`
	PreviousMonthlyEnergy              string `json:"previous_monthly_energy"`
	MonthlyFee                         string `json:"monthly_fee"`
	MonthlyEnergy                      string `json:"monthly_energy"`
	BillMode                           string `json:"bill_mode"`
	PowerMarket                        string `json:"power_market"`
	BillDay                            string `json:"bill_day"`
	Price                              string `json:"price"`
	PriceBase                          string `json:"price_base"`
	FirstTierPrice                     string `json:"first_tier_price"`
	FirstTierEnergy                    string `json:"first_tier_energy"`
	SecondTierPrice                    string `json:"second_tier_price"`
	SecondTierEnergy                   string `json:"second_tier_energy"`
	ThirdTierPrice                     string `json:"third_tier_price"`
	ThirdTierEnergy                    string `json:"third_tier_energy"`
	Bustype                            string `json:"bustype"`
	Busflags                           string `json:"busflags"`
	ReferenceBus                       string `json:"reference_bus"`
	MaximumVoltageError                string `json:"maximum_voltage_error"`
	Voltage1                           string `json:"voltage_1"`
	Voltage2                           string `json:"voltage_2"`
	VoltageN                           string `json:"voltage_N"`
	Voltage12                          string `json:"voltage_12"`
	Voltage1N                          string `json:"voltage_1N"`
	Voltage2N                          string `json:"voltage_2N"`
	PrerotatedCurrent1                 string `json:"prerotated_current_1"`
	PrerotatedCurrent2                 string `json:"prerotated_current_2"`
	PrerotatedCurrent12                string `json:"prerotated_current_12"`
	ResidentialNominalCurrent1         string `json:"residential_nominal_current_1"`
	ResidentialNominalCurrent2         string `json:"residential_nominal_current_2"`
	ResidentialNominalCurrent12        string `json:"residential_nominal_current_12"`
	ResidentialNominalCurrent1Real     string `json:"residential_nominal_current_1_real"`
	ResidentialNominalCurrent1Imag     string `json:"residential_nominal_current_1_imag"`
	ResidentialNominalCurrent2Real     string `json:"residential_nominal_current_2_real"`
	ResidentialNominalCurrent2Imag     string `json:"residential_nominal_current_2_imag"`
	ResidentialNominalCurrent12Real    string `json:"residential_nominal_current_12_real"`
	ResidentialNominalCurrent12Imag    string `json:"residential_nominal_current_12_imag"`
	Current1                           string `json:"current_1"`
	Current2                           string `json:"current_2"`
	CurrentN                           string `json:"current_N"`
	Current1Real                       string `json:"current_1_real"`
	Current2Real                       string `json:"current_2_real"`
	CurrentNReal                       string `json:"current_N_real"`
	Current1Reac                       string `json:"current_1_reac"`
	Current2Reac                       string `json:"current_2_reac"`
	CurrentNReac                       string `json:"current_N_reac"`
	Current12                          string `json:"current_12"`
	Current12Real                      string `json:"current_12_real"`
	Current12Reac                      string `json:"current_12_reac"`
	Power1                             string `json:"power_1"`
	Power2                             string `json:"power_2"`
	Power12                            string `json:"power_12"`
	Power1Real                         string `json:"power_1_real"`
	Power2Real                         string `json:"power_2_real"`
	Power12Real                        string `json:"power_12_real"`
	Power1Reac                         string `json:"power_1_reac"`
	Power2Reac                         string `json:"power_2_reac"`
	Power12Reac                        string `json:"power_12_reac"`
	Shunt1                             string `json:"shunt_1"`
	Shunt2                             string `json:"shunt_2"`
	Shunt12                            string `json:"shunt_12"`
	Impedance1                         string `json:"impedance_1"`
	Impedance2                         string `json:"impedance_2"`
	Impedance12                        string `json:"impedance_12"`
	Impedance1Real                     string `json:"impedance_1_real"`
	Impedance2Real                     string `json:"impedance_2_real"`
	Impedance12Real                    string `json:"impedance_12_real"`
	Impedance1Reac                     string `json:"impedance_1_reac"`
	Impedance2Reac                     string `json:"impedance_2_reac"`
	Impedance12Reac                    string `json:"impedance_12_reac"`
	AccTempCurrent1                    string `json:"acc_temp_current_1"`
	AccTempCurrent2                    string `json:"acc_temp_current_2"`
	AccTempCurrentN                    string `json:"acc_temp_current_N"`
	AccTempCurrent12                   string `json:"acc_temp_current_12"`
	AccTempPower1                      string `json:"acc_temp_power_1"`
	AccTempPower2                      string `json:"acc_temp_power_2"`
	AccTempPower12                     string `json:"acc_temp_power_12"`
	AccTempShunt1                      string `json:"acc_temp_shunt_1"`
	AccTempShunt2                      string `json:"acc_temp_shunt_2"`
	AccTempShunt12                     string `json:"acc_temp_shunt_12"`
	HousePresent                       string `json:"house_present"`
	ResetDisabledIslandState           string `json:"reset_disabled_island_state"`
	GFAEnable                          string `json:"GFA_enable"`
	GFAFreqLowTrip                     string `json:"GFA_freq_low_trip"`
	GFAFreqHighTrip                    string `json:"GFA_freq_high_trip"`
	GFAVoltLowTrip                     string `json:"GFA_volt_low_trip"`
	GFAVoltHighTrip                    string `json:"GFA_volt_high_trip"`
	GFAReconnectTime                   string `json:"GFA_reconnect_time"`
	GFAFreqDisconnectTime              string `json:"GFA_freq_disconnect_time"`
	GFAVoltDisconnectTime              string `json:"GFA_volt_disconnect_time"`
	GFAStatus                          string `json:"GFA_status"`
	ServiceStatus                      string `json:"service_status"`
	ServiceStatusDouble                string `json:"service_status_double"`
	PreviousUptime                     string `json:"previous_uptime"`
	CurrentUptime                      string `json:"current_uptime"`
	TopologicalParent                  string `json:"topological_parent"`
	FrequencyMeasureType               string `json:"frequency_measure_type"`
	SfmTf                              string `json:"sfm_Tf"`
	PllKp                              string `json:"pll_Kp"`
	PllKi                              string `json:"pll_Ki"`
	MeasuredAngle1                     string `json:"measured_angle_1"`
	MeasuredFrequency1                 string `json:"measured_frequency_1"`
	MeasuredAngle2                     string `json:"measured_angle_2"`
	MeasuredFrequency2                 string `json:"measured_frequency_2"`
	MeasuredAngle12                    string `json:"measured_angle_12"`
	MeasuredFrequency12                string `json:"measured_frequency_12"`
	MeasuredFrequency                  string `json:"measured_frequency"`
	Phases                             string `json:"phases"`
	NominalVoltage                     string `json:"nominal_voltage"`
	ViolationDetected                  string `json:"violation_detected"`
	Class                              string `json:"class"`
}

func (tm TriplexMeterData) className() string {
	return "triplex_meter"
}
